server.port=8080

# AI API
ai.base-url=${AI_BASE_URL:http://localhost:8000}

# DB 설정 (도커)
spring.datasource.url=${SPRING_DATASOURCE_URL}?useSSL=false&serverTimezone=Asia/Seoul
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
